const productosStock = [
    {id: 1, 
    name: "Cordero con piel de lobo",
    grape: "Malbec",
    price: 400,
    year: 2020,
    Vineyard: "Mosquita Muerta Wines",
    image: "https://www.espaciovino.com.ar/media/default/0001/61/thumb_60952_default_big.jpeg"},
    {id:2,
    name:"Domiciano cosecha noctura",
    grape:"Cabernet Franc",
    price:1200,
    year:2019,
    Vineyard: "Domiciano",
    image:"https://www.espaciovino.com.ar/media/default/0001/61/thumb_60550_default_medium.jpeg"},
    {id:3,
    name:"El joven equilibrista",
    grape:"Malbec",
    price:750,
    year:2019,
    Vineyard:"Circus Wines",
    image:"https://cepadevinos.com/wp-content/uploads/2017/07/El_Joven_Equilibrista_Malbec_qjn2ay.jpg" },
    {id:4,
    name:"Animal - Orgánico",
    grape:"Malbec",
    price:900,
    year:2019,
    Vineyard:"Natural Vineyard",
    image:"https://cepadevinos.com/wp-content/uploads/2016/09/Animal_Malbec_Organico.jpg"},
    {id:5,
    name:"Pardillos",
    grape:"Malbec",
    price:950,
    year:2020,
    Vineyard:"Pardillos",
    image:"https://cepadevinos.com/wp-content/uploads/2017/07/Padrillos_Malbec_c0itbw.jpg"},
    {id:6,
    name:"Sapo de otro pozo",
    grape:"Malbec",
    price:900,
    year:2019,
    Vineyard:"Mosquita Muerta Wines",
    image:"https://www.espaciovino.com.ar/media/default/0001/59/thumb_58716_default_big.jpeg"}
];

export default productosStock;